"""task fields

Revision ID: 534cdaeca2a5
Revises: 5b5b4ee079e0
Create Date: 2026-02-09 18:05:29.550790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534cdaeca2a5'
down_revision: Union[str, Sequence[str], None] = '5b5b4ee079e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('tasks', sa.Column('result', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'result')
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
