"""add indexes

Revision ID: f91994e2df14
Revises: d928862e3ea2
Create Date: 2026-02-14 18:53:43.772009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91994e2df14'
down_revision: Union[str, Sequence[str], None] = 'd928862e3ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_taskrun_status', 'TaskRun', ['status'], unique=False)
    op.create_index('ix_taskrun_task_id', 'TaskRun', ['task_id'], unique=False)
    op.create_index('ix_task_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('ix_task_owner_id', 'tasks', ['owner_id'], unique=False)
    op.create_index('ix_task_status', 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_task_status', table_name='tasks')
    op.drop_index('ix_task_owner_id', table_name='tasks')
    op.drop_index('ix_task_created_at', table_name='tasks')
    op.drop_index('ix_taskrun_task_id', table_name='TaskRun')
    op.drop_index('ix_taskrun_status', table_name='TaskRun')
    # ### end Alembic commands ###
